export const SearchFlights = {
    getFlights() {
        return [
            {
                "id_trip": "19491",
                "name_trip": "Ставрополь - Москва",
                "id_from_point": "1",
                "from_name_point": "Ставрополь",
                "from_address_point": "проспект Карла Маркса 1А",
                "from_yam": "45.055522,41.998846",
                "from_name": "Ставрополь Ж/Д",
                "id_to_point": "190",
                "to_name_point": "Москва",
                "to_address_point": "г. Москва Киевское шоссе, 23-й километр, 1, стр. 1",
                "to_yam": "55.620926,37.421308",
                "to_name": "Москва АВ Саларьево",
                "date_trip": "2024-03-20",
                "time_trip": "09:30",
                "date_arrival_trip": "2024-03-21",
                "time_arrival_trip": "07:30",
                "time_duration_trip": "22:00",
                "full_ticket_price": "2800",
                "child_ticket_price": "1400",
                "baggage_price": "0",
                "booking_price": "0",
                "markup_ticket_price": "0",
                "markup_child_price": "0",
                "markup_baggage_price": "0",
                "class_reis": "0",
                "total_full_ticket_price": "2800",
                "total_child_ticket_price": "1400",
                "total_baggage_price": "0",
                "ticket_id_2": "16483",
                "carriers": "ИП Яцунов С.П.",
                "source": "evrotrans",
                "seats_trip": "^",
                "count_available_seats_trip": 0,
                "bus_config": {
                    "1": {
                        "1": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "tualet+2+1+Туалет",
                            "busy-seat+1+1+69",
                            "busy-seat+1+1+65",
                            "busy-seat+1+1+61",
                            "busy-seat+1+1+57",
                            "stol+2+1+Стол",
                            "busy-seat+1+1+53",
                            "prohod+1+1+_",
                            "voditel+1+1+_"
                        ],
                        "2": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "Breake",
                            "seat+1+1+70",
                            "seat+1+1+66",
                            "seat+1+1+62",
                            "busy-seat+1+1+58",
                            "Breake",
                            "busy-seat+1+1+54",
                            "prohod+1+1+_",
                            "prohod+1+1+_"
                        ],
                        "3": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_"
                        ],
                        "4": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "exit+2+1+Выход/Вход",
                            "busy-seat+1+1+72",
                            "seat+1+1+68",
                            "busy-seat+1+1+64",
                            "seat+1+1+60",
                            "stol+2+1+Стол",
                            "seat+1+1+56",
                            "busy-seat+1+1+86",
                            "exit+2+1+Выход/Вход"
                        ],
                        "5": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "Breake",
                            "busy-seat+1+1+71",
                            "seat+1+1+67",
                            "busy-seat+1+1+63",
                            "busy-seat+1+1+59",
                            "Breake",
                            "seat+1+1+55",
                            "busy-seat+1+1+85",
                            "Breake"
                        ]
                    },
                    "2": {
                        "1": [
                            "busy-seat+1+1+83",
                            "busy-seat+1+1+81",
                            "busy-seat+1+1+79",
                            "busy-seat+1+1+75",
                            "seat+1+1+73",
                            "busy-seat+1+1+49",
                            "busy-seat+1+1+45",
                            "busy-seat+1+1+37",
                            "busy-seat+1+1+33",
                            "busy-seat+1+1+29",
                            "busy-seat+1+1+25",
                            "busy-seat+1+1+21",
                            "busy-seat+1+1+17",
                            "busy-seat+1+1+13",
                            "busy-seat+1+1+9",
                            "busy-seat+1+1+5",
                            "busy-seat+1+1+1",
                            "Breake"
                        ],
                        "2": [
                            "busy-seat+1+1+84",
                            "busy-seat+1+1+82",
                            "busy-seat+1+1+80",
                            "busy-seat+1+1+76",
                            "busy-seat+1+1+74",
                            "busy-seat+1+1+50",
                            "busy-seat+1+1+46",
                            "busy-seat+1+1+38",
                            "busy-seat+1+1+34",
                            "busy-seat+1+1+30",
                            "busy-seat+1+1+26",
                            "busy-seat+1+1+22",
                            "busy-seat+1+1+18",
                            "busy-seat+1+1+14",
                            "busy-seat+1+1+10",
                            "busy-seat+1+1+6",
                            "busy-seat+1+1+2",
                            "Breake"
                        ],
                        "3": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "tv+1+1+ТВ",
                            "Breake"
                        ],
                        "4": [
                            "busy-seat+1+1+78",
                            "busy-seat+1+1+52",
                            "busy-seat+1+1+48",
                            "busy-seat+1+1+44",
                            "busy-seat+1+1+42",
                            "Breake",
                            "lest+2+2+Лестница",
                            "busy-seat+1+1+40",
                            "busy-seat+1+1+36",
                            "busy-seat+1+1+32",
                            "busy-seat+1+1+28",
                            "busy-seat+1+1+24",
                            "busy-seat+1+1+20",
                            "busy-seat+1+1+16",
                            "busy-seat+1+1+12",
                            "busy-seat+1+1+8",
                            "busy-seat+1+1+4",
                            "Breake"
                        ],
                        "5": [
                            "busy-seat+1+1+77",
                            "busy-seat+1+1+51",
                            "busy-seat+1+1+47",
                            "busy-seat+1+1+43",
                            "busy-seat+1+1+41",
                            "Breake",
                            "Breake",
                            "busy-seat+1+1+39",
                            "busy-seat+1+1+35",
                            "busy-seat+1+1+31",
                            "busy-seat+1+1+27",
                            "busy-seat+1+1+23",
                            "busy-seat+1+1+19",
                            "busy-seat+1+1+15",
                            "busy-seat+1+1+11",
                            "busy-seat+1+1+7",
                            "busy-seat+1+1+3",
                            "Breake"
                        ]
                    }
                }
            },
            {
                "id_trip": "19453",
                "name_trip": "Ставрополь - Москва",
                "id_from_point": "1",
                "from_name_point": "Ставрополь",
                "from_address_point": "проспект Карла Маркса 1А",
                "from_yam": "45.055522,41.998846",
                "from_name": "Ставрополь Ж/Д",
                "id_to_point": "190",
                "to_name_point": "Москва",
                "to_address_point": "г. Москва Киевское шоссе, 23-й километр, 1, стр. 1",
                "to_yam": "55.620926,37.421308",
                "to_name": "Москва АВ Саларьево",
                "date_trip": "2024-03-20",
                "time_trip": "15:30",
                "date_arrival_trip": "2024-03-21",
                "time_arrival_trip": "12:00",
                "time_duration_trip": "20:30",
                "full_ticket_price": "3000",
                "child_ticket_price": "1500",
                "baggage_price": "0",
                "booking_price": "0",
                "markup_ticket_price": "0",
                "markup_child_price": "0",
                "markup_baggage_price": "0",
                "class_reis": "0",
                "total_full_ticket_price": "3000",
                "total_child_ticket_price": "1500",
                "total_baggage_price": "0",
                "ticket_id_2": "1",
                "carriers": "ИП Яцунов С.П.",
                "source": "evrotrans",
                "seats_trip": "^",
                "count_available_seats_trip": 0,
                "bus_config": {
                    "1": {
                        "1": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "tualet+2+1+Туалет",
                            "busy-seat+1+1+69",
                            "busy-seat+1+1+65",
                            "busy-seat+1+1+61",
                            "busy-seat+1+1+57",
                            "stol+2+1+Стол",
                            "busy-seat+1+1+53",
                            "prohod+1+1+_",
                            "voditel+1+1+_"
                        ],
                        "2": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "Breake",
                            "busy-seat+1+1+70",
                            "busy-seat+1+1+66",
                            "busy-seat+1+1+62",
                            "busy-seat+1+1+58",
                            "Breake",
                            "busy-seat+1+1+54",
                            "prohod+1+1+_",
                            "prohod+1+1+_"
                        ],
                        "3": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_"
                        ],
                        "4": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "exit+2+1+Выход/Вход",
                            "busy-seat+1+1+72",
                            "busy-seat+1+1+68",
                            "busy-seat+1+1+64",
                            "busy-seat+1+1+60",
                            "stol+2+1+Стол",
                            "busy-seat+1+1+56",
                            "busy-seat+1+1+86",
                            "exit+2+1+Выход/Вход"
                        ],
                        "5": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "Breake",
                            "busy-seat+1+1+71",
                            "busy-seat+1+1+67",
                            "busy-seat+1+1+63",
                            "busy-seat+1+1+59",
                            "Breake",
                            "busy-seat+1+1+55",
                            "busy-seat+1+1+85",
                            "Breake"
                        ]
                    },
                    "2": {
                        "1": [
                            "busy-seat+1+1+83",
                            "busy-seat+1+1+81",
                            "busy-seat+1+1+79",
                            "busy-seat+1+1+75",
                            "busy-seat+1+1+73",
                            "busy-seat+1+1+49",
                            "busy-seat+1+1+45",
                            "busy-seat+1+1+37",
                            "busy-seat+1+1+33",
                            "busy-seat+1+1+29",
                            "busy-seat+1+1+25",
                            "busy-seat+1+1+21",
                            "busy-seat+1+1+17",
                            "busy-seat+1+1+13",
                            "busy-seat+1+1+9",
                            "busy-seat+1+1+5",
                            "busy-seat+1+1+1",
                            "Breake"
                        ],
                        "2": [
                            "busy-seat+1+1+84",
                            "busy-seat+1+1+82",
                            "busy-seat+1+1+80",
                            "busy-seat+1+1+76",
                            "busy-seat+1+1+74",
                            "busy-seat+1+1+50",
                            "busy-seat+1+1+46",
                            "busy-seat+1+1+38",
                            "busy-seat+1+1+34",
                            "busy-seat+1+1+30",
                            "busy-seat+1+1+26",
                            "busy-seat+1+1+22",
                            "busy-seat+1+1+18",
                            "busy-seat+1+1+14",
                            "busy-seat+1+1+10",
                            "busy-seat+1+1+6",
                            "busy-seat+1+1+2",
                            "Breake"
                        ],
                        "3": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "tv+1+1+ТВ",
                            "Breake"
                        ],
                        "4": [
                            "busy-seat+1+1+78",
                            "busy-seat+1+1+52",
                            "busy-seat+1+1+48",
                            "busy-seat+1+1+44",
                            "busy-seat+1+1+42",
                            "Breake",
                            "lest+2+2+Лестница",
                            "busy-seat+1+1+40",
                            "busy-seat+1+1+36",
                            "busy-seat+1+1+32",
                            "busy-seat+1+1+28",
                            "busy-seat+1+1+24",
                            "busy-seat+1+1+20",
                            "busy-seat+1+1+16",
                            "busy-seat+1+1+12",
                            "busy-seat+1+1+8",
                            "busy-seat+1+1+4",
                            "Breake"
                        ],
                        "5": [
                            "busy-seat+1+1+77",
                            "busy-seat+1+1+51",
                            "busy-seat+1+1+47",
                            "busy-seat+1+1+43",
                            "busy-seat+1+1+41",
                            "Breake",
                            "Breake",
                            "busy-seat+1+1+39",
                            "busy-seat+1+1+35",
                            "busy-seat+1+1+31",
                            "busy-seat+1+1+27",
                            "busy-seat+1+1+23",
                            "busy-seat+1+1+19",
                            "busy-seat+1+1+15",
                            "busy-seat+1+1+11",
                            "busy-seat+1+1+7",
                            "busy-seat+1+1+3",
                            "Breake"
                        ]
                    }
                }
            },
            {
                "id_trip": "19470",
                "name_trip": "Ставрополь - Москва",
                "id_from_point": "1",
                "from_name_point": "Ставрополь",
                "from_address_point": "проспект Карла Маркса 1А",
                "from_yam": "45.055522,41.998846",
                "from_name": "Ставрополь Ж/Д",
                "id_to_point": "190",
                "to_name_point": "Москва",
                "to_address_point": "г. Москва Киевское шоссе, 23-й километр, 1, стр. 1",
                "to_yam": "55.620926,37.421308",
                "to_name": "Москва АВ Саларьево",
                "date_trip": "2024-03-20",
                "time_trip": "19:00",
                "date_arrival_trip": "2024-03-21",
                "time_arrival_trip": "15:30",
                "time_duration_trip": "20:30",
                "full_ticket_price": "3000",
                "child_ticket_price": "1500",
                "baggage_price": "0",
                "booking_price": "0",
                "markup_ticket_price": "0",
                "markup_child_price": "0",
                "markup_baggage_price": "0",
                "class_reis": "0",
                "total_full_ticket_price": "3000",
                "total_child_ticket_price": "1500",
                "total_baggage_price": "0",
                "ticket_id_2": "32",
                "carriers": "ИП Яцунов С.П.",
                "source": "evrotrans",
                "seats_trip": "46^47^48^52^53",
                "count_available_seats_trip": 5,
                "bus_config": {
                    "1": {
                        "1": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "tualet+2+1+Туалет",
                            "busy-seat+1+1+69",
                            "busy-seat+1+1+65",
                            "busy-seat+1+1+61",
                            "busy-seat+1+1+57",
                            "stol+2+1+Стол",
                            "seat+1+1+53",
                            "prohod+1+1+_",
                            "voditel+1+1+_"
                        ],
                        "2": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "Breake",
                            "busy-seat+1+1+70",
                            "busy-seat+1+1+66",
                            "busy-seat+1+1+62",
                            "busy-seat+1+1+58",
                            "Breake",
                            "busy-seat+1+1+54",
                            "prohod+1+1+_",
                            "prohod+1+1+_"
                        ],
                        "3": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_"
                        ],
                        "4": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "exit+2+1+Выход/Вход",
                            "busy-seat+1+1+72",
                            "busy-seat+1+1+68",
                            "busy-seat+1+1+64",
                            "busy-seat+1+1+60",
                            "stol+2+1+Стол",
                            "busy-seat+1+1+56",
                            "busy-seat+1+1+86",
                            "exit+2+1+Выход/Вход"
                        ],
                        "5": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "Breake",
                            "busy-seat+1+1+71",
                            "busy-seat+1+1+67",
                            "busy-seat+1+1+63",
                            "busy-seat+1+1+59",
                            "Breake",
                            "busy-seat+1+1+55",
                            "busy-seat+1+1+85",
                            "Breake"
                        ]
                    },
                    "2": {
                        "1": [
                            "busy-seat+1+1+83",
                            "busy-seat+1+1+81",
                            "busy-seat+1+1+79",
                            "busy-seat+1+1+75",
                            "busy-seat+1+1+73",
                            "busy-seat+1+1+49",
                            "busy-seat+1+1+45",
                            "busy-seat+1+1+37",
                            "busy-seat+1+1+33",
                            "busy-seat+1+1+29",
                            "busy-seat+1+1+25",
                            "busy-seat+1+1+21",
                            "busy-seat+1+1+17",
                            "busy-seat+1+1+13",
                            "busy-seat+1+1+9",
                            "busy-seat+1+1+5",
                            "busy-seat+1+1+1",
                            "Breake"
                        ],
                        "2": [
                            "busy-seat+1+1+84",
                            "busy-seat+1+1+82",
                            "busy-seat+1+1+80",
                            "busy-seat+1+1+76",
                            "busy-seat+1+1+74",
                            "busy-seat+1+1+50",
                            "seat+1+1+46",
                            "busy-seat+1+1+38",
                            "busy-seat+1+1+34",
                            "busy-seat+1+1+30",
                            "busy-seat+1+1+26",
                            "busy-seat+1+1+22",
                            "busy-seat+1+1+18",
                            "busy-seat+1+1+14",
                            "busy-seat+1+1+10",
                            "busy-seat+1+1+6",
                            "busy-seat+1+1+2",
                            "Breake"
                        ],
                        "3": [
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "prohod+1+1+_",
                            "tv+1+1+ТВ",
                            "Breake"
                        ],
                        "4": [
                            "busy-seat+1+1+78",
                            "seat+1+1+52",
                            "seat+1+1+48",
                            "busy-seat+1+1+44",
                            "busy-seat+1+1+42",
                            "Breake",
                            "lest+2+2+Лестница",
                            "busy-seat+1+1+40",
                            "busy-seat+1+1+36",
                            "busy-seat+1+1+32",
                            "busy-seat+1+1+28",
                            "busy-seat+1+1+24",
                            "busy-seat+1+1+20",
                            "busy-seat+1+1+16",
                            "busy-seat+1+1+12",
                            "busy-seat+1+1+8",
                            "busy-seat+1+1+4",
                            "Breake"
                        ],
                        "5": [
                            "busy-seat+1+1+77",
                            "busy-seat+1+1+51",
                            "seat+1+1+47",
                            "busy-seat+1+1+43",
                            "busy-seat+1+1+41",
                            "Breake",
                            "Breake",
                            "busy-seat+1+1+39",
                            "busy-seat+1+1+35",
                            "busy-seat+1+1+31",
                            "busy-seat+1+1+27",
                            "busy-seat+1+1+23",
                            "busy-seat+1+1+19",
                            "busy-seat+1+1+15",
                            "busy-seat+1+1+11",
                            "busy-seat+1+1+7",
                            "busy-seat+1+1+3",
                            "Breake"
                        ]
                    }
                }
            }
        ]
    },

};
